#!/usr/local/bin/perl -w

use strict;

BEGIN {
        chdir "$ENV{HOME}/src/qt/4/PerlQt";
        unshift @INC, 'blib/arch';
        unshift @INC, 'blib/lib';
}

use Qt;
use Devel::Peek;

#my $widget = Qt::QWidget();
my $splitter = Qt::QSplitter();
#Dump($widget);
my $label1 = Qt::QLabel("Hello World!", $splitter);
my $label2 = Qt::QLabel("You Rock!", $splitter);
$splitter->show();
Qt::qapp()->exec();
