#!/usr/local/bin/perl -w
use strict;

BEGIN {
        chdir "$ENV{HOME}/src/qt/4/PerlQt";
        unshift @INC, 'blib/arch';
        unshift @INC, 'blib/lib';
}

package myStringListModel;
use Qt;
use Qt::isa qw(Qt::QAbstractListModel);
use Devel::Peek;

my @stringList;

sub NEW {
    my $class = shift;
    my( $stringListRef, $parent ) = @_;
    $class->SUPER::NEW();
    @stringList = @{$stringListRef};
}

sub rowCount {
    my( $parent ) = @_;
    return scalar @stringList;
}

sub data {
    my( $index, $role ) = @_;

    if (!$index->isValid()){
        return Qt::QVariant();
    }

    my $modelRow = $index->row();
    if ($modelRow >= scalar @stringList){
        return Qt::QVariant();
    }

    if ($role == Qt::Qt::DisplayRole()) {
        return Qt::QVariant($stringList[$modelRow]);
    }
    else {
        return Qt::QVariant();
    }
}

sub headerData {
    my ( $section, $orientation, $role ) = @_;
    if ( $role != Qt::Qt::DisplayRole() ) {
        return Qt::QVariant();
    }

    if ( $orientation == Qt::Qt::Horizontal() ) {
        return Qt::QVariant("Column " . $section);
    }
    else {
        return Qt::QVariant("Row " . $section);
    }
}

sub flags {
    my ( $index ) = @_;

    if (!$index->isValid()) {
        return Qt::Qt::ItemIsEnabled();
    }

    return SUPER->flags(this, $index) | Qt::Qt::ItemIsEditable();
}

sub setData {
    my( $index, $value, $role ) = @_;
    if ($index->isValid() && $role == Qt::Qt::EditRole()) { 
        @stringList[$index->row()] = $value->toString();
        this->dataChanged($index, $index); # emit
        return 1;
    }
    return 0;
}
1;

package main;

use Qt;
#use Qt::debug qw(all);
use myStringListModel;

my $model = myStringListModel( [qw( Hello world you are awesome )] );
my $numRows = $model->rowCount();

my $splitter = Qt::QSplitter();

my $tableview = Qt::QTableView($splitter);
$tableview->setModel( $model );

my $listview = Qt::QListView($splitter);
$listview->setModel( $model );

$tableview->setSelectionModel( $listview->selectionModel() );
$splitter->show();
exit Qt::appexec;
