#!/usr/local/bin/perl -w

use strict;

BEGIN {
#        chdir "$ENV{HOME}/src/qt/4/PerlQt";
        unshift @INC, 'blib/arch';
        unshift @INC, 'blib/lib';
}

use QtSimple;
use Devel::Peek;

my $label = QtSimple::QLabel("Hello Awesome!");
#Dump($label);
$label->show();
QtSimple::appexec();
