#!/usr/local/bin/perl -w

use strict;

BEGIN {
        chdir "$ENV{HOME}/src/qt/4/PerlQt";
        unshift @INC, 'blib/arch';
        unshift @INC, 'blib/lib';
}

use Qt;
use Devel::Peek;

my $label = Qt::QLabel("Hello Awesome!");
#Dump($label);
$label->show();
Qt::qapp()->exec();
