#!/usr/local/bin/perl -w
use strict;
use blib;

package Button::Hello;
use Qt;
use Qt::isa qw(Qt::QPushButton);

my $this;

sub NEW
{
    shift->SUPER::NEW(@_);
    this->resize(130, 40);
}

#sub resize {
    #SUPER->resize(130,40);
#}

1;

package main;

use Qt;
use Button::Hello;

my $w = Button::Hello("Hello World!", undef);
$w->show;
exit Qt::qapp()->exec();
