#!/usr/local/bin/perl -w
use strict;

BEGIN {
    chdir "$ENV{HOME}/src/qt/4/PerlQt";
    unshift @INC, 'blib/arch';
    unshift @INC, 'blib/lib';
}

package Button::Hello;
use Qt;
use Qt::isa qw(Qt::QPushButton);

my $this;

sub NEW
{
  $this = bless( shift->SUPER::NEW(@_[0..2]), ' Button');
  $this->resize(130, 40);
  return $this;
}

sub resize {
    printf( "In custom resize\n" );
    $this->resize(130,40);
}

1;

package main;

use Qt;
use Button::Hello;

my $w = Button::Hello("Hello World!", undef);
$w->show;
exit Qt::appexec();
