#!/usr/local/bin/perl -w

BEGIN {
        chdir "$ENV{HOME}/src/qt/4/PerlQt";
        unshift @INC, 'blib/arch';
        unshift @INC, 'blib/lib';
}

use Qt;
use Devel::Peek;

#my $app = Qt::QApplication( 1, \@ARGV );
my $splitter = Qt::QSplitter();

my $model = Qt::QDirModel();
my $modelIndex = $model->index('/');

my $table1 = Qt::QTableView( $splitter );
$table1->setModel( $model );
$table1->setRootIndex( $modelIndex );

my $table2 = Qt::QTableView( $splitter );
$table2->setModel( $model );
$table2->setRootIndex( $modelIndex );

$table1->setSelectionModel( $table2->selectionModel() );

$splitter->setWindowTitle( 'Two views onto the same directory model' );
$splitter->show();
exit Qt::appexec();
#exit $app->exec();
