#!/usr/local/bin/perl -w

BEGIN {
        chdir "$ENV{HOME}/src/qt/4/PerlQtSimple";
        unshift @INC, 'blib/arch';
        unshift @INC, 'blib/lib';
}

use strict;
use QtSimple;
use Devel::Peek;

#my $app = QtSimple::QApplication( \@ARGV );
my $model = QtSimple::QDirModel();
my $parentIndex = $model->index(QtSimple::QDir::currentPath());
my $numRows = $model->rowCount( $parentIndex );
my $numCols = $model->columnCount( $parentIndex );

my @output;
for( my $row = 0; $row < $numRows; ++$row ){
    my @rowContents;
    for( my $col = 0; $col < $numCols; ++$col ){
        my $index = $model->index($row, $col, $parentIndex);
        push @rowContents, sprintf( "%-15s", $model->data($index, 0)->toString());
    }
    push @output, join '', @rowContents;
}

END {
    print join "\n", @output;
    print "\n";
}
